"""Monitoring utilities for Scry_Ingestor."""

from .metrics import (
    INGESTION_ACTIVE_REQUESTS,
    INGESTION_ATTEMPTS,
    INGESTION_ERRORS,
    INGESTION_PAYLOAD_SIZE_BYTES,
    INGESTION_SLA_VIOLATIONS,
    PROCESSING_DURATION,
    TRACE_SPAN_DURATION,
    TRACE_SPANS_CREATED,
    VALIDATION_ERRORS,
    VALIDATION_WARNINGS,
    decrement_active_requests,
    increment_active_requests,
    observe_payload_size,
    observe_processing_duration,
    observe_trace_span_duration,
    record_ingestion_attempt,
    record_ingestion_error,
    record_sla_violation,
    record_trace_span_created,
    record_validation_error,
    record_validation_warning,
)
from .tracing import (
    TraceSpan,
    ensure_correlation_id,
    extract_correlation_id_from_headers,
    generate_correlation_id,
    get_correlation_id,
    inject_correlation_id_into_headers,
    set_correlation_id,
    trace_span,
)

__all__ = [
    # Metrics
    "INGESTION_ATTEMPTS",
    "INGESTION_ERRORS",
    "PROCESSING_DURATION",
    "INGESTION_SLA_VIOLATIONS",
    "INGESTION_ACTIVE_REQUESTS",
    "INGESTION_PAYLOAD_SIZE_BYTES",
    "TRACE_SPANS_CREATED",
    "TRACE_SPAN_DURATION",
    "VALIDATION_ERRORS",
    "VALIDATION_WARNINGS",
    "record_ingestion_attempt",
    "record_ingestion_error",
    "observe_processing_duration",
    "record_sla_violation",
    "increment_active_requests",
    "decrement_active_requests",
    "observe_payload_size",
    "record_trace_span_created",
    "observe_trace_span_duration",
    "record_validation_error",
    "record_validation_warning",
    # Tracing
    "TraceSpan",
    "get_correlation_id",
    "set_correlation_id",
    "generate_correlation_id",
    "ensure_correlation_id",
    "trace_span",
    "extract_correlation_id_from_headers",
    "inject_correlation_id_into_headers",
]
